sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t narawittub4822/docker-react .

script:
  - docker run -e CI=true narawittub4822/docker-react yarn run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-319498131033"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
