sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t narawittub4822/docker-react .

script:
  - docker run -e CI=true narawittub4822/docker-react yarn run test
